begin;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  retailcrm_id bigint not null unique,
  external_id text,
  number text,
  created_at timestamptz not null,
  status text,
  customer_name text,
  phone text,
  total_sum numeric(14, 2) not null check (total_sum >= 0),
  currency text not null default 'KZT',
  source text,
  raw_json jsonb not null,
  synced_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_orders_created_at_desc
  on public.orders (created_at desc);

create index if not exists idx_orders_total_sum_desc
  on public.orders (total_sum desc);

create table if not exists public.sync_state (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.alerts_sent (
  retailcrm_id bigint primary key references public.orders (retailcrm_id) on delete cascade,
  sent_at timestamptz not null default timezone('utc', now())
);

alter table public.orders enable row level security;
alter table public.sync_state enable row level security;
alter table public.alerts_sent enable row level security;

grant select on public.orders to anon, authenticated;
revoke all on public.sync_state from anon, authenticated;
revoke all on public.alerts_sent from anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'orders'
      and policyname = 'Public can read orders'
  ) then
    create policy "Public can read orders"
      on public.orders
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

commit;
